# ~/.config/pipewire/pipewire.conf.d/eq.conf

context.modules = [
{   name = libpipewire-module-parametric-equalizer
    args = {
        remote.name = "pipewire-0"
        equalizer.filepath = "/home/lee/.config/pipewire/pipewire.conf.d/peq_trutheargate_5128.txt"
        equalizer.description = "Parametric EQ Sink"
        audio.channels = 2
        audio.position = [FL, FR]
        capture.props = {
          node.name = "Parametric EQ input"
        }
        playback.props = {
          node.name = "Parametric EQ output"
        }
    }
}
]
