vim.cmd [[colorscheme catppuccin]]
-- vim.cmd [[hi Normal ctermbg=none guibg=none]]
-- vim.cmd [[hi NormalFloat ctermbg=none guibg=none]]
-- vim.cmd [[hi TelescopeNormal ctermbg=none guibg=none]]
-- vim.cmd [[hi TelescopeBorder ctermbg=none guibg=none]]
-- vim.cmd [[hi TelescopePromptNormal ctermbg=none guibg=none]]
-- vim.cmd [[hi TelescopeResultsNormal ctermbg=none guibg=none]]
-- vim.cmd [[hi TelescopePreviewNormal ctermbg=none guibg=none]]
