#!/usr/bin/env bash

SESH="mdr"

tmux has-session -t $SESH 2>/dev/null

if [ $? != 0 ]; then
	tmux new-session -d -s $SESH -n "editor"
	tmux send-keys -t $SESH:editor "cd ~/projects/prd-aws-soc-core" C-m
	tmux send-keys -t $SESH:editor "nvim ." C-m

	tmux new-window -t $SESH -n "shell"
	tmux send-keys -t $SESH:editor "cd ~/projects/prd-aws-soc-core" C-m
	
    tmux new-window -t $SESH -n "git"
	tmux send-keys -t $SESH:editor "cd ~/projects/prd-aws-soc-core" C-m
	tmux send-keys -t $SESH:git "git status" C-m

	tmux select-window -t $SESH:editor
fi

tmux attach-session -t $SESH
